{
 "title": "LED Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Colored LED Chart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ESP32\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"etatLed\" and r[\"_field\"] == \"value\" and exists r[\"_value\"])\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value,\r\n      state: if r._value == 0 then \"Green\"\r\n             else if r._value == 1 then \"Red\"\r\n             else if r._value == 2 then \"Orange\"\r\n             else \"Unknown\"\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "Etat LED",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ESP32\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"etatLed\" and r[\"_field\"] == \"value\" and exists r[\"_value\"])\r\n"
    }
   ]
  },
  {
   "title": "LED color bar gauge",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ESP32\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"etatLed\" and r[\"_field\"] == \"value\" and exists r[\"_value\"])\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value,\r\n      state: if r._value == 0 then \"Green\"\r\n             else if r._value == 1 then \"Red\"\r\n             else if r._value == 2 then \"Orange\"\r\n             else \"Unknown\"\r\n  }))\r\n  |> group(columns: [\"state\"])\r\n  |> count()\r\n"
    }
   ]
  },
  {
   "title": "Répartitions état parking",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ESP32\") \r\n  |> range(start: -1h) \r\n  |> filter(fn: (r) => r._measurement == \"etatParking\" and r[\"_field\"] == \"value\" and exists r[\"_value\"])\r\n  |> map(fn: (r) => ({\r\n      status: if r._value == 0 then \"FREE\"\r\n              else if r._value == 1 then \"OCCUPIED\"\r\n              else if r._value == 2 then \"RESERVED\"\r\n              else \"UNKNOWN\",\r\n      count: 1\r\n  }))\r\n  |> group(columns: [\"status\"])\r\n  |> sum(column: \"count\")\r\n"
    }
   ]
  },
  {
   "title": "Parking state Color Gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ESP32\") \r\n  |> range(start: -1h) \r\n  |> filter(fn: (r) => r._measurement == \"etatParking\" and r[\"_field\"] == \"value\" and exists r[\"_value\"])\r\n  |> map(fn: (r) => ({\r\n      status: if r._value == 0 then \"FREE\"\r\n              else if r._value == 1 then \"OCCUPIED\"\r\n              else if r._value == 2 then \"RESERVED\"\r\n              else \"UNKNOWN\",\r\n      count: 1\r\n  }))\r\n  |> group(columns: [\"status\"])\r\n  |> sum(column: \"count\")\r\n"
    }
   ]
  }
 ]
}